"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='고유 식별자'),
    sa.Column('location', sa.String(length=50), nullable=False, comment='보관 위치'),
    sa.Column('purchase_date', sa.Date(), nullable=False, comment='구매일'),
    sa.Column('sale_date', sa.Date(), nullable=True, comment='판매일'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='모델명'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='제품명'),
    sa.Column('size', sa.String(length=20), nullable=True, comment='사이즈'),
    sa.Column('vendor', sa.String(length=100), nullable=False, comment='구매처'),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False, comment='가격'),
    sa.Column('notes', sa.Text(), nullable=True, comment='메모'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 인덱스 생성
    op.create_index('idx_model_name', 'inventory_items', ['model_name', 'name'], unique=False)
    op.create_index('idx_sale_date', 'inventory_items', ['sale_date'], unique=False)
    
    # SQLite에서는 FULLTEXT 인덱스를 지원하지 않으므로 일반 인덱스 사용
    op.create_index('idx_fulltext_search', 'inventory_items', ['name', 'model_name', 'vendor', 'notes'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fulltext_search', table_name='inventory_items')
    op.drop_index('idx_sale_date', table_name='inventory_items')
    op.drop_index('idx_model_name', table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
