"""Add barcode field and barcode table

Revision ID: 0002
Revises: 0001
Create Date: 2024-01-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # inventory_items 테이블에 barcode 컬럼 추가
    op.add_column('inventory_items', sa.Column('barcode', sa.String(length=50), nullable=True, comment='바코드'))
    
    # barcodes 테이블 생성
    op.create_table('barcodes',
    sa.Column('barcode', sa.String(length=50), nullable=False, comment='바코드 (Primary Key)'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='모델명'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='제품명'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('barcode')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # barcodes 테이블 삭제
    op.drop_table('barcodes')
    
    # inventory_items 테이블에서 barcode 컬럼 삭제
    op.drop_column('inventory_items', 'barcode')
    
    # ### end Alembic commands ###
